import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Metric } from '../../entities/metric.entity';
import {
  AdminAccount,
  AdminAlert,
  AdminAlertRule,
  AdminCategory,
  AdminChatSession,
  AdminCommission,
  AdminCustomer,
  AdminDevice,
  AdminDeviceCalibration,
  AdminDeviceFault,
  AdminDeviceModel,
  AdminDistRule,
  AdminDistributor,
  AdminInventory,
  AdminMsgTemplate,
  AdminNotice,
  AdminOpLog,
  AdminOrder,
  AdminPackage,
  AdminPaymentRecord,
  AdminPointRecord,
  AdminPointRule,
  AdminProduct,
  AdminRanking,
  AdminRechargePackage,
  AdminRechargeRecord,
  AdminRegionDividend,
  AdminRole,
  AdminStockLog,
  AdminTechApply,
  AdminTechnician,
  AdminWaterRecord,
  AdminWithdrawal,
  AdminWorkorder,
} from '../../entities/admin.entities';
import { AdminController } from './admin.controller';
import { AdminService } from './admin.service';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      Metric,
      AdminCategory,
      AdminProduct,
      AdminOrder,
      AdminDevice,
      AdminDeviceModel,
      AdminWorkorder,
      AdminTechnician,
      AdminDistributor,
      AdminCommission,
      AdminWithdrawal,
      AdminDistRule,
      AdminCustomer,
      AdminRechargePackage,
      AdminRechargeRecord,
      AdminAlert,
      AdminAlertRule,
      AdminRanking,
      AdminPointRule,
      AdminPointRecord,
      AdminInventory,
      AdminStockLog,
      AdminRole,
      AdminAccount,
      AdminOpLog,
      AdminNotice,
      AdminMsgTemplate,
      AdminTechApply,
      AdminDeviceFault,
      AdminDeviceCalibration,
      AdminWaterRecord,
      AdminChatSession,
      AdminPaymentRecord,
      AdminPackage,
      AdminRegionDividend,
    ]),
  ],
  controllers: [AdminController],
  providers: [AdminService],
})
export class AdminModule {}
